### ISSUE TITLE
Keep going bro, this is really good 

### ISSUE THREAD

**Issue by ibbatta** [nitin42/Creating-a-JavaScript-UI-library#1]
This is not an issue but a cheer at you for creating this interesting repo.
P.s. If you want any help in future (also for translations into italian) let me know!

**Comment by nitin42** [comment]
Wow!! Thank you so much. I could really use your help in translating this tutorial to Italian language. I will post an update here once I am done. Such a nice gesture!

**Comment by ibbatta** [comment]
It's a community so "let's community together" ahahah
Let me know when things go on :)

**Comment by ibbatta** [comment]
+1

**Comment by aolko** [comment]
@nitin42 so, what's the hold up?
